channels:
  - conda-forge
dependencies:
  - python
  - future
  - numpy
  - scipy
  - imageio
  - matplotlib
  - pyfftw
  - scikit-video
  - ffmpeg
  - tabulate
  - scikit-image
  - pytictoc
  
  - pip:
    - git+https://github.com/bwohlberg/sporco
